### PR TITLE
Turn on eol-last

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by merih** [comment]
I'm in favor of this, but let's hear other teams' responses.

**Review by ceylanismail — CHANGES_REQUESTED** [review]
I really don't like trailing commas, or eol, or any kind. To me, they are the legacy conventions come from the old times to fix another tools/frameworks/protocols inconvenience.

It's same as adding the `,` to the last JSON attribute, to fix the git diff visualization.

I'd be sad if @zeplin/web team agrees and add this to the `browser.js` but wouldn't disagree - for the base.js, I don't agree with the change.

**Review by berkcebi — COMMENTED** [review]
Regardless of the history behind this convention, I just feel like we need to enable this rule—either `always` or `never`—and stick to one thing in all of our repos. 😅

I prefer `always` though, since that's the default for most editors/file viewers (like GitHub).

**Comment by mertkahyaoglu** [comment]
I'm just closing this since we all couldn't agree on this.

**Pull request closed without merging**
